punishproducer functionality added
Remmeauth/remprotocol pull request #105
Opened 2019-11-12 19:35 UTC by Art17

New action punishprod

eosio_global_rem_state
      microseconds producer_max_inactivity_time = eosio::minutes(30);
      microseconds producer_inactivity_punishment_period = eosio::days(30);

producer_info
     time_point last_block_time
     time_point top21_chosen_time

2019-11-12 22:12 UTC, roman-tik requested changes
please also add tests

2019-11-12 22:12 UTC, roman-tik commented on contracts/contracts/rem.system/src/producer_pay.cpp
> +         for (size_t producer_index = 0; producer_index < _gstate.last_schedule.size(); producer_index++) {
do we need a separate `for` here? maybe join it with the previous one?

2019-11-12 22:12 UTC, roman-tik commented on contracts/contracts/rem.system/src/producer_pay.cpp
> +            }
lets's add `else` here and reduce `active_producers` vector, so the next `for` below iterates only over the newly added active producers without the need to do that `find_if`.

2019-11-12 22:12 UTC, roman-tik commented on contracts/contracts/rem.system/src/rem.system.cpp
> +   require_auth(_self);
```suggestion
   require_auth(get_self());
```

2019-11-12 22:12 UTC, roman-tik commented on contracts/contracts/rem.system/src/rem.system.cpp
> +       require_auth(_self);
```suggestion
       require_auth(get_self());
```

2019-11-12 22:12 UTC, roman-tik commented on contracts/contracts/rem.system/src/rem.system.cpp
> +    check( ct - _gremstate.producer_max_inactivity_time > prod->punished_until, "punishment period is not over yet" );
not sure I understood the purpose of this check here

2019-11-13 13:53 UTC, Art17 commented on contracts/contracts/rem.system/src/rem.system.cpp
> +    check( ct - _gremstate.producer_max_inactivity_time > prod->punished_until, "punishment period is not over yet" );
Removed.

2019-11-13 13:54 UTC, Art17 commented on contracts/contracts/rem.system/src/rem.system.cpp
> +       require_auth(_self);
Done.

2019-11-13 13:54 UTC, Art17 commented on contracts/contracts/rem.system/src/rem.system.cpp
> +   require_auth(_self);
Done.

2019-11-13 13:55 UTC, Art17 commented on contracts/contracts/rem.system/src/producer_pay.cpp
> +            }
What for?

2019-11-13 14:01 UTC, Art17 commented on contracts/contracts/rem.system/src/producer_pay.cpp
> +         for (size_t producer_index = 0; producer_index < _gstate.last_schedule.size(); producer_index++) {
Done.

2019-12-02 18:38 UTC, roman-tik approved these changes

2019-12-02 18:39 UTC, merged