add(voting): after registration during unlock period, if prod have >=…
Remmeauth/remprotocol pull request #54
Opened 2019-08-21 14:55 UTC by AndriiAndrusyshyn

…250'000.0000 staked tokens, stake lock period reset to zero.

add(test): case for testing new logic.

## Change Description

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

2019-08-21 15:13 UTC, mark-tsyrulnyk requested changes

2019-08-21 15:13 UTC, mark-tsyrulnyk commented on contracts/contracts/rem.system/src/voting.cpp
> +             if(voter.locked_stake >= 250'000'0000ll){
@AndriiAndrusyshyn please use `system_contract::producer_stake_threshold`

2019-08-21 15:13 UTC, mark-tsyrulnyk commented on contracts/contracts/rem.system/src/voting.cpp
> +                 v.stake_lock_time = eosio::time_point(eosio::days(0));
@AndriiAndrusyshyn it should be `now` and not `0`

2019-08-21 15:13 UTC, mark-tsyrulnyk commented on contracts/contracts/rem.system/src/voting.cpp
> +             if(voter.locked_stake >= 250'000'0000ll){
@AndriiAndrusyshyn it seems could be done easier; you can keep `_voters.modify` out of the braces but calculate lock time. e.g.
```
const auto lock_time = voter.locked_stake >= system_contract::producer_stake_threshold ? current_time_point()
                                                                                       : current_time_point() + _gstate.stake_lock_period;

_voters.modify(voter, producer, [&](auto &v) {
        v.stake_lock_time = lock_time
        v.locked_stake = tot.own_stake_amount;
    }
);
```

2019-08-23 10:15 UTC, mark-tsyrulnyk requested changes

2019-08-23 10:15 UTC, mark-tsyrulnyk commented on unittests/rem_voting_test.cpp
> +    uint64_t microseconds_since_epoch_of_iso_string( const fc::variant& v ) {
@AndriiAndrusyshyn if it possible, let this method return `microseconds`, time should be represented by time types

2019-08-23 10:15 UTC, mark-tsyrulnyk commented on unittests/rem_voting_test.cpp
> +      const auto first_test_amount = asset(2'000'000'000);
@AndriiAndrusyshyn please move these consts closer to the first usage.

2019-08-23 10:15 UTC, mark-tsyrulnyk commented on unittests/rem_voting_test.cpp
> +      const auto initial_lock_period = 15552000000000; // amount of microseconds equal to 180 days
@AndriiAndrusyshyn can we use `fc::days( 180 )` here?

2019-08-23 10:15 UTC, mark-tsyrulnyk commented on unittests/rem_voting_test.cpp
> +      const auto initial_time = 1577836806000000;
@AndriiAndrusyshyn `fc::microseconds( 1577836806000000 )`

2019-08-23 10:15 UTC, mark-tsyrulnyk commented on unittests/rem_voting_test.cpp
> +         auto time_to_unlock = std::max(fc::microseconds(current_stake_lock_time) - fc::microseconds(current_time), microseconds{});
@AndriiAndrusyshyn why do we need `max` here?

2019-08-23 10:15 UTC, mark-tsyrulnyk commented on unittests/rem_voting_test.cpp
> +         auto new_stake_lock_time = current_time + fc::microseconds(static_cast<int64_t>(prev_rate * (time_to_unlock.count()))).count() +
@AndriiAndrusyshyn you don't need to repeat business logic in test (because then you need write tests for tests), just comparing results with some expected values.

2019-08-23 10:15 UTC, mark-tsyrulnyk commented on unittests/rem_voting_test.cpp
> +BOOST_FIXTURE_TEST_CASE( stake_lock_unlock_period_test, voting_tester ) {
@AndriiAndrusyshyn `regprod_during_unlock_period_test`

2019-08-23 10:15 UTC, mark-tsyrulnyk commented on unittests/rem_voting_test.cpp
> +      auto voter = get_voter_info( "proda" );
@AndriiAndrusyshyn remove redundant line above, and move it closer to the first usage

2019-08-23 10:15 UTC, mark-tsyrulnyk commented on unittests/rem_voting_test.cpp
> +       BOOST_REQUIRE_EQUAL(current_time, microseconds_since_epoch_of_iso_string(voter["stake_lock_time"]));
@AndriiAndrusyshyn could you please add a check that locked_stake equal to staked

2019-08-23 10:15 UTC, mark-tsyrulnyk commented on unittests/rem_voting_test.cpp
> +       BOOST_CHECK( 0 != microseconds_since_epoch_of_iso_string(voter["stake_lock_time"]));
@AndriiAndrusyshyn please fix indentation

2019-08-23 10:15 UTC, mark-tsyrulnyk commented on unittests/rem_voting_test.cpp
> +       //Skip 150 days to call unregistration
@AndriiAndrusyshyn please replace 150 -> 180 where applicable

2019-08-23 10:16 UTC, mark-tsyrulnyk commented on contracts/contracts/rem.system/src/voting.cpp
> +          printf("%lld\n", current_time_point());
@AndriiAndrusyshyn please remove this

2019-08-23 15:11 UTC, me-vadim commented on contracts/contracts/rem.system/src/voting.cpp
> +      const auto &voter = _voters.get(producer.value, "user has no resources");
In does_satisfy_stake_requirement( producer ) lookup of voters table is executed.
Here you added _voters.get(producer.value, "user has no resources");

Consider removing does_satisfy_stake_requirement
Something like this:
const auto &voter = _voters.get(producer.value, "user has no resources");
check( voter->staked >= producer_stake_threshold, stake_err );

2019-08-27 11:57 UTC, mark-tsyrulnyk approved these changes

2019-08-27 13:18 UTC, me-vadim approved these changes

2019-08-27 13:18 UTC, me-vadim commented on contracts/contracts/rem.system/src/voting.cpp
>        static const auto stake_err = "user should stake at least "s + asset(producer_stake_threshold, core_symbol()).to_string() + " to become a producer"s;
move declaration of variable to the place where it is used

2019-08-27 13:20 UTC, merged