Feature involve top22 25 prods in schedule
Remmeauth/remprotocol pull request #62
Opened 2019-09-13 09:51 UTC by me-vadim

- [ x ] Consensus Changes

Implemented rotation mechanics.
Every twelve hours new rotation will be set.
Rotation is replacement of one of top21 producers with one of n first standby producers.
Top producers are placed in rotation queue where first is the one that was longer than others. The same is for standby queue.

If either rotated out top21 producer stopped beeing top21 or rotated in standby producer stopped beeing in rotated standby list (became top21 or moved out of top(21+n)) during rotation period then rotation pair is dropped and new schedule will be proposed with all top21 in it.

2019-09-13 12:49 UTC, mark-tsyrulnyk commented on contracts/contracts/rem.system/src/voting.cpp
> +         producers.push_back(item);
@me-vadim it's seems that we don't need this transformed view; you can just use `top_producers` instead

2019-09-13 12:49 UTC, mark-tsyrulnyk commented on contracts/contracts/rem.system/src/rotation.cpp
> +      auto schedule = std::move(top_prods);
@me-vadim why we need this move? can we just use `top_prods` here?

2019-09-13 13:12 UTC, mark-tsyrulnyk commented on contracts/contracts/rem.system/src/rotation.cpp
> +            _grotation.prods_by_rotation_time.pop_front();
@me-vadim it seems like we can use `std::rotate` here

2019-09-13 13:25 UTC, mark-tsyrulnyk commented on contracts/contracts/rem.system/src/rotation.cpp
> +      else if (_grotation.bp_out != name(0) && _grotation.sbp_in != name(0)) { //check if we need to drop rotation pair
@me-vadim I suggest to rewrite it next way to improve readability
```
else if (_grotation.bp_out != name(0) && _grotation.sbp_in != name(0)) { //check if we need to drop rotation pair
    //reset rotation pair if bp_out is not in active producers or if sbp_in is not in top standby producers
    const auto bp_it = std::find_if( std::begin(top_prods), std::end(top_prods), 
                            [this](const auto& prod_key) { 
                                return prod_key.producer_name == _grotation.bp_out;
                            }
                       );

    const auto stadby_it = std::find_if( std::begin(rotating_standby), std::end(rotating_standby), _grotation.sbp_in );

    if ( bp_it == std::end(top_prods) || standby_it == std::end(rotating_standby) ) {
        _grotation.bp_out = name(0);
        _grotation.sbp_in = name(0);
    }
}
```

2019-09-17 00:57 UTC, roman-tik requested changes
1. Let's always rotate 21st producer out
2. Let's add more tests to cover reward distribution by to_rewards

2019-10-04 07:11 UTC, merged